image: quay.io/samsung_cnct/helm-registry-agent

variables:
  CHART_REL: ${CI_COMMIT_SHA}
  CHART_NAME: krak8s-api

cache:
  untracked: true

build-branch:
  stage: build
  only:
    - branches
    - master
  script:
  - CHART_VER=${CI_COMMIT_REF_NAME} envsubst < build/Chart.yaml.in > ${CHART_NAME}/Chart.yaml
  - cat krak8s-api/Chart.yaml

build-tags:
  stage: test
  only:
    - tags
  script:
  - CHART_VER=${CI_COMMIT_TAG} envsubst < build/Chart.yaml.in > ${CHART_NAME}/Chart.yaml
  - cat krak8s-api/Chart.yaml

test:
  stage: test
  variables:
    GIT_STRATEGY: fetch
  script:
  - helm lint ${CHART_NAME}

deploy-branches:
  stage: deploy
  only:
    - branches
    - master
  variables:
    GIT_STRATEGY: fetch
  script:
  - helm registry login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
  - helm registry push ${REGISTRY_HOST}/${REGISTRY_CHART_NAME} -c alpha ${CHART_NAME}

deploy-tags:
  stage: deploy
  only:
    - tags
  variables:
    GIT_STRATEGY: fetch
  script:
  - helm registry login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
  - helm registry push ${REGISTRY_HOST}/${REGISTRY_CHART_NAME} -c stable ${CHART_NAME}

