image: quay.io/samsung_cnct/helm-registry-agent

variables:
  CHART_VER: ${CI_COMMIT_REF_NAME}
  CHART_REL: ${CI_COMMIT_SHA}
  CHART_NAME: krak8s-api

build-branch:
  stage: build
  only:
    - branches
    - master
  script:
  - envsubst < build/Chart.yaml.in > ${CHART_NAME}/Chart.yaml

build-tags:
  stage: test
  only:
    - tags
  script:
  - CHART_VER=${CI_COMMIT_TAG} envsubst < build/Chart.yaml.in > ${CHART_NAME}/Chart.yaml

test:
  stage: test
  script:
  - helm lint ${CHART_NAME}

deploy:
  stage: deploy
  script:
  - helm registry login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
  - helm registry push ${REGISTRY_HOST}/${REGISTRY_CHART_NAME} -c stable ${CHART_NAME}


