## Launchdock Image and Image Tag
## ref: https://hub.docker.com/r/reactioncommerce/launchdock/tags/
##
image: quay.io/reactioncommerce/krak8s
imageTag: latest
imagePullPolicy: IfNotPresent
imagePullSecret: 

## Should the service be LoadBalancer, NodePort or ClusterIP
## If you're using ingress, ClusterIP should be a solid choice
##
serviceType: ClusterIP

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 500m
    memory: 768Mi

scheduling:
  affinity:
    node:
      type: requiredDuringSchedulingIgnoredDuringExecution
      labels:
#      - key: iamalabelkey
#        operator: In
#        values: ["value1", "value2"]
  tolerations:
#  - key: iamataintkey
#    value: taintvalue
#    effect: NoSchedule

networkPolicy:
  ingress:
#    enabled: true
#    namespaceLabels:
#      - key: tenant
#        value: customer1
#    podLabels:
#      - key: app
#        value: frontend
